module.exports = {
    REGISTER: 'USER REGISTERED',
    VERIFY_EMAIL_PENDING: 'VERIFY EMAIL PENDING',
    LOGIN: 'USER LOGGED IN',
    GOOGLE_LOGIN: 'USER LOGGED IN WITH GOOGLE',
    FACEBOOK_LOGIN: 'USER LOGGED IN WITH FACEBOOK',
    BECOME_SELLER: 'USER BECAME A SELLER',
    UPDATE_PROFILE: 'USER UPDATED PROFILE',
    LOGOUT: 'USER LOGGED OUT',
};
